// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATvvEqVAT_sv8SUoP-QGP5KcyGgT4fqoY',
    appId: '1:317708209514:web:86b959b104744e2c606913',
    messagingSenderId: '317708209514',
    projectId: 'pos-medicine-app',
    authDomain: 'pos-medicine-app.firebaseapp.com',
    storageBucket: 'pos-medicine-app.firebasestorage.app',
    measurementId: 'G-9BDQLG1V0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEbTdxqNHFYEDGC_Sy4iUr8AIZGoF5s7o',
    appId: '1:317708209514:android:a23a2f8626ca928e606913',
    messagingSenderId: '317708209514',
    projectId: 'pos-medicine-app',
    storageBucket: 'pos-medicine-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPtpOrbQ53Q4iGcLIaADzZsDJxNFTB7Bs',
    appId: '1:317708209514:ios:2493d8c2f5fb045d606913',
    messagingSenderId: '317708209514',
    projectId: 'pos-medicine-app',
    storageBucket: 'pos-medicine-app.firebasestorage.app',
    iosClientId: '317708209514-6od7fntceabavsvm7huf4okr4u3gg99b.apps.googleusercontent.com',
    iosBundleId: 'com.example.lembreteRemedio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPtpOrbQ53Q4iGcLIaADzZsDJxNFTB7Bs',
    appId: '1:317708209514:ios:2493d8c2f5fb045d606913',
    messagingSenderId: '317708209514',
    projectId: 'pos-medicine-app',
    storageBucket: 'pos-medicine-app.firebasestorage.app',
    iosClientId: '317708209514-6od7fntceabavsvm7huf4okr4u3gg99b.apps.googleusercontent.com',
    iosBundleId: 'com.example.lembreteRemedio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATvvEqVAT_sv8SUoP-QGP5KcyGgT4fqoY',
    appId: '1:317708209514:web:e1bf8f72bf6d6eb7606913',
    messagingSenderId: '317708209514',
    projectId: 'pos-medicine-app',
    authDomain: 'pos-medicine-app.firebaseapp.com',
    storageBucket: 'pos-medicine-app.firebasestorage.app',
    measurementId: 'G-BLX41JN228',
  );

}